language: java

jdk:
  - oraclejdk8

sudo: required
dist: trusty

script:
  - mvn package --fail-at-end
  - mkdir build
  - cp target/*.war build

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWSAccessKeyId
  secret_access_key: $AWSSecretKey
  bucket: builds.opentosca.org
  acl: public_read
  local_dir: build/
  upload-dir: ui/$TRAVIS_BRANCH
  region: eu-central-1
  on:
    all_branches: true
