language: node_js

node_js:
  - "node"

# we build at Ubuntu 14.04 (Trusty Thar) as we want to use a more recent Ubuntu version
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-8-jdk maven

script:
  - ./mvnw package --fail-at-end
  - mkdir build/wars
  - cp build/target/*.war build/wars

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWSAccessKeyId
  secret_access_key: $AWSSecretKey
  bucket: builds.opentosca.org
  acl: public_read
  local_dir: build/wars/
  upload-dir: ui/$TRAVIS_BRANCH
  region: eu-central-1
  on:
    all_branches: true
